
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'F01AD9948EA15156A6CA9678166830E3'
    
_lr_action_items = {'LOAD':([0,],[10,]),'LOADI':([0,],[1,]),',':([29,30,31,32,33,34,50,],[35,36,37,38,39,40,54,]),'XOR':([0,],[11,]),'SUB':([0,],[2,]),'BB':([0,],[3,]),'SHIFT':([0,],[4,]),'JMP':([0,],[8,]),'$end':([9,20,24,41,45,49,52,53,55,57,],[0,-1,-10,-9,-5,-14,-15,-8,-2,-16,]),'AND':([0,],[17,]),'NUMBER':([3,5,8,12,22,23,25,26,27,28,35,38,42,43,44,46,47,56,],[-12,-13,-11,24,29,30,31,32,33,34,41,45,48,49,50,51,52,57,]),'ADD':([0,],[18,]),'R':([1,2,4,6,7,10,11,13,14,15,16,17,18,19,21,36,37,40,54,],[-6,-21,-7,22,23,-3,-19,25,26,27,-4,-17,-20,28,-18,43,44,47,56,]),'STORE':([0,],[16,]),'NOT':([0,],[19,]),'[':([35,39,],[42,46,]),'BEQ':([0,],[5,]),']':([48,51,],[53,55,]),'OR':([0,],[21,]),'STOREI':([0,],[6,]),'CMP':([0,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cod4':([0,],[12,]),'cod5':([0,],[13,]),'cod2':([0,],[14,]),'statement':([0,],[9,]),'cod1':([0,],[15,]),'expression':([0,],[20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','intermedio_maquina.py',84),
  ('expression -> cod1 R NUMBER , [ NUMBER ]','expression',7,'p_tipo1','intermedio_maquina.py',88),
  ('cod1 -> LOAD','cod1',1,'p_cod1','intermedio_maquina.py',92),
  ('cod1 -> STORE','cod1',1,'p_cod1','intermedio_maquina.py',93),
  ('expression -> cod2 R NUMBER , NUMBER','expression',5,'p_tipo2','intermedio_maquina.py',100),
  ('cod2 -> LOADI','cod2',1,'p_cod2','intermedio_maquina.py',104),
  ('cod2 -> SHIFT','cod2',1,'p_cod2','intermedio_maquina.py',105),
  ('expression -> STOREI R NUMBER , [ NUMBER ]','expression',7,'p_tipo3','intermedio_maquina.py',112),
  ('expression -> STOREI R NUMBER , NUMBER','expression',5,'p_tipo3_1','intermedio_maquina.py',116),
  ('expression -> cod4 NUMBER','expression',2,'p_tipo4','intermedio_maquina.py',120),
  ('cod4 -> JMP','cod4',1,'p_cod4','intermedio_maquina.py',124),
  ('cod4 -> BB','cod4',1,'p_cod4','intermedio_maquina.py',125),
  ('cod4 -> BEQ','cod4',1,'p_cod4','intermedio_maquina.py',126),
  ('expression -> CMP R NUMBER , R NUMBER','expression',6,'p_tipo5','intermedio_maquina.py',135),
  ('expression -> NOT R NUMBER , R NUMBER','expression',6,'p_tipo6','intermedio_maquina.py',140),
  ('expression -> cod5 R NUMBER , R NUMBER , R NUMBER','expression',9,'p_tipo7','intermedio_maquina.py',144),
  ('cod5 -> AND','cod5',1,'p_cod5','intermedio_maquina.py',148),
  ('cod5 -> OR','cod5',1,'p_cod5','intermedio_maquina.py',149),
  ('cod5 -> XOR','cod5',1,'p_cod5','intermedio_maquina.py',150),
  ('cod5 -> ADD','cod5',1,'p_cod5','intermedio_maquina.py',151),
  ('cod5 -> SUB','cod5',1,'p_cod5','intermedio_maquina.py',152),
]
