
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '8368B2A17BA49D6C8BC73100A56A2194'
    
_lr_action_items = {'LOAD':([0,],[1,]),'LOADI':([0,],[2,]),'BB':([0,],[3,]),'SHIFT':([0,],[5,]),'JMP':([0,],[4,]),'NUMBER':([13,14,15,16,19,21,24,],[17,18,19,20,23,25,26,]),'R':([1,2,5,7,8,10,],[-3,-6,-7,15,-4,16,]),'STORE':([0,],[8,]),'[':([3,4,6,11,17,20,],[-11,-10,14,-12,21,24,]),'BEQ':([0,],[11,]),']':([18,25,26,],[22,27,28,]),'STOREI':([0,],[13,]),'$end':([9,12,22,23,27,28,],[0,-1,-9,-5,-8,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cod2':([0,],[7,]),'cod4':([0,],[6,]),'expression':([0,],[12,]),'statement':([0,],[9,]),'cod1':([0,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','tarea4.py',87),
  ('expression -> cod1 R NUMBER [ NUMBER ]','expression',6,'p_tipo1','tarea4.py',91),
  ('cod1 -> LOAD','cod1',1,'p_cod1','tarea4.py',95),
  ('cod1 -> STORE','cod1',1,'p_cod1','tarea4.py',96),
  ('expression -> cod2 R NUMBER NUMBER','expression',4,'p_tipo2','tarea4.py',103),
  ('cod2 -> LOADI','cod2',1,'p_cod2','tarea4.py',107),
  ('cod2 -> SHIFT','cod2',1,'p_cod2','tarea4.py',108),
  ('expression -> STOREI NUMBER [ NUMBER ]','expression',5,'p_tipo3','tarea4.py',115),
  ('expression -> cod4 [ NUMBER ]','expression',4,'p_tipo4','tarea4.py',119),
  ('cod4 -> JMP','cod4',1,'p_cod4','tarea4.py',123),
  ('cod4 -> BB','cod4',1,'p_cod4','tarea4.py',124),
  ('cod4 -> BEQ','cod4',1,'p_cod4','tarea4.py',125),
]
